package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.Date;

public class InformeJuridicoModificado {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_CODIGO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String codigoExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.CON_DESCRIPCION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String descripcionContrato;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.CON_PRESUPUESTO_TOTAL
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal presupuestoTotalContrato;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_F_AUT_GASTO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private Date fechaAutorizacionGastoExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.PROVEEDOR
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String proveedor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_UC_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idUnidadContratacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_SECUENCIA
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal secuenciaExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_NAT_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idNaturaleza;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_AÑO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal añoExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_TS_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idTipoServicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.EXP_EST_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idEstado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.CON_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idContrato;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.F_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private Date fechaCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.UC_ACR
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String acronimoUnidadContratacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.TIPO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal tipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.MOD_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idModificado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORME_AJ_MOD_V.F_PETICION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private Date fPeticion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_ID
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdExpediente() {
        return idExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_ID
     *
     * @param idExpediente the value for INFORME_AJ_MOD_V.EXP_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdExpediente(BigDecimal idExpediente) {
        this.idExpediente = idExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_CODIGO
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_CODIGO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getCodigoExpediente() {
        return codigoExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_CODIGO
     *
     * @param codigoExpediente the value for INFORME_AJ_MOD_V.EXP_CODIGO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setCodigoExpediente(String codigoExpediente) {
        this.codigoExpediente = codigoExpediente == null ? null : codigoExpediente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.CON_DESCRIPCION
     *
     * @return the value of INFORME_AJ_MOD_V.CON_DESCRIPCION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getDescripcionContrato() {
        return descripcionContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.CON_DESCRIPCION
     *
     * @param descripcionContrato the value for INFORME_AJ_MOD_V.CON_DESCRIPCION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setDescripcionContrato(String descripcionContrato) {
        this.descripcionContrato = descripcionContrato == null ? null : descripcionContrato.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.CON_PRESUPUESTO_TOTAL
     *
     * @return the value of INFORME_AJ_MOD_V.CON_PRESUPUESTO_TOTAL
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getPresupuestoTotalContrato() {
        return presupuestoTotalContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.CON_PRESUPUESTO_TOTAL
     *
     * @param presupuestoTotalContrato the value for INFORME_AJ_MOD_V.CON_PRESUPUESTO_TOTAL
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setPresupuestoTotalContrato(BigDecimal presupuestoTotalContrato) {
        this.presupuestoTotalContrato = presupuestoTotalContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_F_AUT_GASTO
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_F_AUT_GASTO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Date getFechaAutorizacionGastoExpediente() {
        return fechaAutorizacionGastoExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_F_AUT_GASTO
     *
     * @param fechaAutorizacionGastoExpediente the value for INFORME_AJ_MOD_V.EXP_F_AUT_GASTO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setFechaAutorizacionGastoExpediente(Date fechaAutorizacionGastoExpediente) {
        this.fechaAutorizacionGastoExpediente = fechaAutorizacionGastoExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.PROVEEDOR
     *
     * @return the value of INFORME_AJ_MOD_V.PROVEEDOR
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getProveedor() {
        return proveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.PROVEEDOR
     *
     * @param proveedor the value for INFORME_AJ_MOD_V.PROVEEDOR
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor == null ? null : proveedor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_UC_ID
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_UC_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdUnidadContratacion() {
        return idUnidadContratacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_UC_ID
     *
     * @param idUnidadContratacion the value for INFORME_AJ_MOD_V.EXP_UC_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdUnidadContratacion(BigDecimal idUnidadContratacion) {
        this.idUnidadContratacion = idUnidadContratacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_SECUENCIA
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_SECUENCIA
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getSecuenciaExpediente() {
        return secuenciaExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_SECUENCIA
     *
     * @param secuenciaExpediente the value for INFORME_AJ_MOD_V.EXP_SECUENCIA
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setSecuenciaExpediente(BigDecimal secuenciaExpediente) {
        this.secuenciaExpediente = secuenciaExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_NAT_ID
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_NAT_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdNaturaleza() {
        return idNaturaleza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_NAT_ID
     *
     * @param idNaturaleza the value for INFORME_AJ_MOD_V.EXP_NAT_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdNaturaleza(BigDecimal idNaturaleza) {
        this.idNaturaleza = idNaturaleza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_AÑO
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_AÑO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getAñoExpediente() {
        return añoExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_AÑO
     *
     * @param añoExpediente the value for INFORME_AJ_MOD_V.EXP_AÑO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setAñoExpediente(BigDecimal añoExpediente) {
        this.añoExpediente = añoExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_TS_ID
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_TS_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdTipoServicio() {
        return idTipoServicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_TS_ID
     *
     * @param idTipoServicio the value for INFORME_AJ_MOD_V.EXP_TS_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdTipoServicio(BigDecimal idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.EXP_EST_ID
     *
     * @return the value of INFORME_AJ_MOD_V.EXP_EST_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdEstado() {
        return idEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.EXP_EST_ID
     *
     * @param idEstado the value for INFORME_AJ_MOD_V.EXP_EST_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdEstado(BigDecimal idEstado) {
        this.idEstado = idEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.CON_ID
     *
     * @return the value of INFORME_AJ_MOD_V.CON_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdContrato() {
        return idContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.CON_ID
     *
     * @param idContrato the value for INFORME_AJ_MOD_V.CON_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdContrato(BigDecimal idContrato) {
        this.idContrato = idContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.F_CREACION
     *
     * @return the value of INFORME_AJ_MOD_V.F_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.F_CREACION
     *
     * @param fechaCreacion the value for INFORME_AJ_MOD_V.F_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.UC_ACR
     *
     * @return the value of INFORME_AJ_MOD_V.UC_ACR
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getAcronimoUnidadContratacion() {
        return acronimoUnidadContratacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.UC_ACR
     *
     * @param acronimoUnidadContratacion the value for INFORME_AJ_MOD_V.UC_ACR
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setAcronimoUnidadContratacion(String acronimoUnidadContratacion) {
        this.acronimoUnidadContratacion = acronimoUnidadContratacion == null ? null : acronimoUnidadContratacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.TIPO
     *
     * @return the value of INFORME_AJ_MOD_V.TIPO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.TIPO
     *
     * @param tipo the value for INFORME_AJ_MOD_V.TIPO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setTipo(BigDecimal tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.MOD_ID
     *
     * @return the value of INFORME_AJ_MOD_V.MOD_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdModificado() {
        return idModificado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.MOD_ID
     *
     * @param idModificado the value for INFORME_AJ_MOD_V.MOD_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdModificado(BigDecimal idModificado) {
        this.idModificado = idModificado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORME_AJ_MOD_V.F_PETICION
     *
     * @return the value of INFORME_AJ_MOD_V.F_PETICION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Date getfPeticion() {
        return fPeticion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORME_AJ_MOD_V.F_PETICION
     *
     * @param fPeticion the value for INFORME_AJ_MOD_V.F_PETICION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setfPeticion(Date fPeticion) {
        this.fPeticion = fPeticion;
    }
}