package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Correo;
import es.ise.ciceron.model.CorreoExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface CorreoMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_CORREOS_V
     *
     * @mbggenerated Thu Aug 25 13:32:16 CEST 2011
     */
    int countByExample(CorreoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_CORREOS_V
     *
     * @mbggenerated Thu Aug 25 13:32:16 CEST 2011
     */
    List<Correo> selectByExample(CorreoExample example);
}