package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Archivo;
import es.ise.ciceron.model.ArchivoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ArchivoMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int countByExample(ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int deleteByExample(ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int insert(Archivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int insertSelective(Archivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<Archivo> selectByExampleWithBLOBs(ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<Archivo> selectByExample(ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    Archivo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByExampleSelective(@Param("record") Archivo record, @Param("example") ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") Archivo record, @Param("example") ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByExample(@Param("record") Archivo record, @Param("example") ArchivoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByPrimaryKeySelective(Archivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByPrimaryKeyWithBLOBs(Archivo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ARCHIVO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByPrimaryKey(Archivo record);
}