package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Contratos;
import es.ise.ciceron.model.ContratosExample;
import java.math.BigDecimal;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ContratosMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(ContratosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<Contratos> selectByExample(ContratosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTRATOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    Contratos selectByPrimaryKey(BigDecimal id);
}