package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Entidades;
import es.ise.ciceron.model.EntidadesExample;
import java.math.BigDecimal;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface EntidadesMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTA.ENTIDADES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(EntidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTA.ENTIDADES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<Entidades> selectByExample(EntidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTA.ENTIDADES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    Entidades selectByPrimaryKey(BigDecimal id);
}