package es.ise.ciceron.mapper;

import es.ise.ciceron.model.ESDocumento;
import es.ise.ciceron.model.ESDocumentoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ESDocumentoMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int countByExample(ESDocumentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int deleteByExample(ESDocumentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int insert(ESDocumento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int insertSelective(ESDocumento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    List<ESDocumento> selectByExample(ESDocumentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    ESDocumento selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int updateByExampleSelective(@Param("record") ESDocumento record, @Param("example") ESDocumentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int updateByExample(@Param("record") ESDocumento record, @Param("example") ESDocumentoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int updateByPrimaryKeySelective(ESDocumento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ES_DOCUMENTOS
     *
     * @mbggenerated Wed Aug 10 09:57:11 CEST 2011
     */
    int updateByPrimaryKey(ESDocumento record);
}