package es.ise.ciceron.mapper;

import es.ise.ciceron.model.FirmantesInformes;
import es.ise.ciceron.model.FirmantesInformesExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface FirmantesInformesMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_FIRMANTES_INFORMES_V
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(FirmantesInformesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_FIRMANTES_INFORMES_V
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<FirmantesInformes> selectByExample(FirmantesInformesExample example);
}