package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Informe;
import es.ise.ciceron.model.InformeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface InformeMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(InformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int deleteByExample(InformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int insert(Informe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int insertSelective(Informe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<Informe> selectByExample(InformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    Informe selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByExampleSelective(@Param("record") Informe record, @Param("example") InformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByExample(@Param("record") Informe record, @Param("example") InformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByPrimaryKeySelective(Informe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByPrimaryKey(Informe record);
}