package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Naturaleza;
import es.ise.ciceron.model.NaturalezaExample;
import java.math.BigDecimal;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface NaturalezaMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATURALEZA
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(NaturalezaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATURALEZA
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<Naturaleza> selectByExample(NaturalezaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATURALEZA
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    Naturaleza selectByPrimaryKey(BigDecimal id);
}