package es.ise.ciceron.mapper;

import es.ise.ciceron.model.TextoInforme;
import es.ise.ciceron.model.TextoInformeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface TextoInformeMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(TextoInformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int deleteByExample(TextoInformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int insert(TextoInforme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int insertSelective(TextoInforme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<TextoInforme> selectByExample(TextoInformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    TextoInforme selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByExampleSelective(@Param("record") TextoInforme record, @Param("example") TextoInformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByExample(@Param("record") TextoInforme record, @Param("example") TextoInformeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByPrimaryKeySelective(TextoInforme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TEXTO_INFORME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByPrimaryKey(TextoInforme record);
}