package es.ise.ciceron.mapper;

import es.ise.ciceron.model.TipoBloquePuntos;
import es.ise.ciceron.model.TipoBloquePuntosExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface TipoBloquePuntosMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int countByExample(TipoBloquePuntosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<TipoBloquePuntos> selectByExample(TipoBloquePuntosExample example);
}