package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Usuario;
import es.ise.ciceron.model.UsuarioExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface UsuarioMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_USUARIOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int countByExample(UsuarioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_USUARIOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<Usuario> selectByExample(UsuarioExample example);
}