package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.Date;

public class TextoInforme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_TEXTO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String texto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_INF_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idInforme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_P_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal idPunto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_U_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String uCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_F_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private Date fCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_U_ACTU
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String uActu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_F_ACTU
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private Date fActu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_P_ORDEN
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private BigDecimal ordenPunto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_TEXTO_INFORME.TEI_P_DESCRIPCION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    private String descripcionPunto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_ID
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_ID
     *
     * @param id the value for AJ_TEXTO_INFORME.TEI_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_TEXTO
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_TEXTO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getTexto() {
        return texto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_TEXTO
     *
     * @param texto the value for AJ_TEXTO_INFORME.TEI_TEXTO
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setTexto(String texto) {
        this.texto = texto == null ? null : texto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_INF_ID
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_INF_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdInforme() {
        return idInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_INF_ID
     *
     * @param idInforme the value for AJ_TEXTO_INFORME.TEI_INF_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdInforme(BigDecimal idInforme) {
        this.idInforme = idInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_P_ID
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_P_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getIdPunto() {
        return idPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_P_ID
     *
     * @param idPunto the value for AJ_TEXTO_INFORME.TEI_P_ID
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setIdPunto(BigDecimal idPunto) {
        this.idPunto = idPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_U_CREACION
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_U_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getuCreacion() {
        return uCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_U_CREACION
     *
     * @param uCreacion the value for AJ_TEXTO_INFORME.TEI_U_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setuCreacion(String uCreacion) {
        this.uCreacion = uCreacion == null ? null : uCreacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_F_CREACION
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_F_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Date getfCreacion() {
        return fCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_F_CREACION
     *
     * @param fCreacion the value for AJ_TEXTO_INFORME.TEI_F_CREACION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setfCreacion(Date fCreacion) {
        this.fCreacion = fCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_U_ACTU
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_U_ACTU
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getuActu() {
        return uActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_U_ACTU
     *
     * @param uActu the value for AJ_TEXTO_INFORME.TEI_U_ACTU
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setuActu(String uActu) {
        this.uActu = uActu == null ? null : uActu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_F_ACTU
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_F_ACTU
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Date getfActu() {
        return fActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_F_ACTU
     *
     * @param fActu the value for AJ_TEXTO_INFORME.TEI_F_ACTU
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setfActu(Date fActu) {
        this.fActu = fActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_P_ORDEN
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_P_ORDEN
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public BigDecimal getOrdenPunto() {
        return ordenPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_P_ORDEN
     *
     * @param ordenPunto the value for AJ_TEXTO_INFORME.TEI_P_ORDEN
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setOrdenPunto(BigDecimal ordenPunto) {
        this.ordenPunto = ordenPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_TEXTO_INFORME.TEI_P_DESCRIPCION
     *
     * @return the value of AJ_TEXTO_INFORME.TEI_P_DESCRIPCION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getDescripcionPunto() {
        return descripcionPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_TEXTO_INFORME.TEI_P_DESCRIPCION
     *
     * @param descripcionPunto the value for AJ_TEXTO_INFORME.TEI_P_DESCRIPCION
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setDescripcionPunto(String descripcionPunto) {
        this.descripcionPunto = descripcionPunto == null ? null : descripcionPunto.trim();
    }

    public void setActualizacion(Date fecha, Usuario usuario) {
        this.fActu = fecha;
        this.uActu = usuario.getIdentificador();
    }

    public void setCreacion(Date fecha, Usuario usuario) {
        this.fCreacion = fecha;
        this.uCreacion = usuario.getIdentificador();
        this.fActu = fecha;
        this.uActu = usuario.getIdentificador();
    }

    public void copyCreacion(TextoInforme source) {
        this.fCreacion = source.fCreacion;
        this.uCreacion = source.uCreacion;
        this.fActu = source.fActu;
        this.uActu = source.uActu;
    }

    public void copyActualizacion(TextoInforme source) {
        this.fActu = source.fActu;
        this.uActu = source.uActu;
    }
}