package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DocumentosESExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public DocumentosESExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdEsDocumentoIsNull() {
            addCriterion("ID_ES_DOCUMENTO is null");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoIsNotNull() {
            addCriterion("ID_ES_DOCUMENTO is not null");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoEqualTo(BigDecimal value) {
            addCriterion("ID_ES_DOCUMENTO =", value, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoNotEqualTo(BigDecimal value) {
            addCriterion("ID_ES_DOCUMENTO <>", value, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoGreaterThan(BigDecimal value) {
            addCriterion("ID_ES_DOCUMENTO >", value, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_ES_DOCUMENTO >=", value, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoLessThan(BigDecimal value) {
            addCriterion("ID_ES_DOCUMENTO <", value, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_ES_DOCUMENTO <=", value, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoIn(List<BigDecimal> values) {
            addCriterion("ID_ES_DOCUMENTO in", values, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoNotIn(List<BigDecimal> values) {
            addCriterion("ID_ES_DOCUMENTO not in", values, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_ES_DOCUMENTO between", value1, value2, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdEsDocumentoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_ES_DOCUMENTO not between", value1, value2, "idEsDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionIsNull() {
            addCriterion("ID_TIPO_OPERACION is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionIsNotNull() {
            addCriterion("ID_TIPO_OPERACION is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO_OPERACION =", value, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionNotEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO_OPERACION <>", value, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionGreaterThan(BigDecimal value) {
            addCriterion("ID_TIPO_OPERACION >", value, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO_OPERACION >=", value, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionLessThan(BigDecimal value) {
            addCriterion("ID_TIPO_OPERACION <", value, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO_OPERACION <=", value, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionIn(List<BigDecimal> values) {
            addCriterion("ID_TIPO_OPERACION in", values, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionNotIn(List<BigDecimal> values) {
            addCriterion("ID_TIPO_OPERACION not in", values, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_TIPO_OPERACION between", value1, value2, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdTipoOperacionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_TIPO_OPERACION not between", value1, value2, "idTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadIsNull() {
            addCriterion("ID_OTRA_UNIDAD is null");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadIsNotNull() {
            addCriterion("ID_OTRA_UNIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadEqualTo(BigDecimal value) {
            addCriterion("ID_OTRA_UNIDAD =", value, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadNotEqualTo(BigDecimal value) {
            addCriterion("ID_OTRA_UNIDAD <>", value, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadGreaterThan(BigDecimal value) {
            addCriterion("ID_OTRA_UNIDAD >", value, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_OTRA_UNIDAD >=", value, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadLessThan(BigDecimal value) {
            addCriterion("ID_OTRA_UNIDAD <", value, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_OTRA_UNIDAD <=", value, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadIn(List<BigDecimal> values) {
            addCriterion("ID_OTRA_UNIDAD in", values, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadNotIn(List<BigDecimal> values) {
            addCriterion("ID_OTRA_UNIDAD not in", values, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_OTRA_UNIDAD between", value1, value2, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andIdOtraUnidadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_OTRA_UNIDAD not between", value1, value2, "idOtraUnidad");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("DESCRIPCION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("DESCRIPCION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("DESCRIPCION =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("DESCRIPCION <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("DESCRIPCION >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("DESCRIPCION <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("DESCRIPCION like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("DESCRIPCION not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("DESCRIPCION in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("DESCRIPCION not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("FECHA is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("FECHA is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterionForJDBCDate("FECHA >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterionForJDBCDate("FECHA <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FECHA <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterionForJDBCDate("FECHA in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterionForJDBCDate("FECHA not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FECHA between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FECHA not between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("TIPO is null");
            return (Criteria) this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("TIPO is not null");
            return (Criteria) this;
        }

        public Criteria andTipoEqualTo(String value) {
            addCriterion("TIPO =", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotEqualTo(String value) {
            addCriterion("TIPO <>", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThan(String value) {
            addCriterion("TIPO >", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(String value) {
            addCriterion("TIPO >=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThan(String value) {
            addCriterion("TIPO <", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThanOrEqualTo(String value) {
            addCriterion("TIPO <=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLike(String value) {
            addCriterion("TIPO like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotLike(String value) {
            addCriterion("TIPO not like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoIn(List<String> values) {
            addCriterion("TIPO in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotIn(List<String> values) {
            addCriterion("TIPO not in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoBetween(String value1, String value2) {
            addCriterion("TIPO between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotBetween(String value1, String value2) {
            addCriterion("TIPO not between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroIsNull() {
            addCriterion("NOMBRE_FICHERO is null");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroIsNotNull() {
            addCriterion("NOMBRE_FICHERO is not null");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroEqualTo(String value) {
            addCriterion("NOMBRE_FICHERO =", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroNotEqualTo(String value) {
            addCriterion("NOMBRE_FICHERO <>", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroGreaterThan(String value) {
            addCriterion("NOMBRE_FICHERO >", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroGreaterThanOrEqualTo(String value) {
            addCriterion("NOMBRE_FICHERO >=", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroLessThan(String value) {
            addCriterion("NOMBRE_FICHERO <", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroLessThanOrEqualTo(String value) {
            addCriterion("NOMBRE_FICHERO <=", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroLike(String value) {
            addCriterion("NOMBRE_FICHERO like", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroNotLike(String value) {
            addCriterion("NOMBRE_FICHERO not like", value, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroIn(List<String> values) {
            addCriterion("NOMBRE_FICHERO in", values, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroNotIn(List<String> values) {
            addCriterion("NOMBRE_FICHERO not in", values, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroBetween(String value1, String value2) {
            addCriterion("NOMBRE_FICHERO between", value1, value2, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andNombreFicheroNotBetween(String value1, String value2) {
            addCriterion("NOMBRE_FICHERO not between", value1, value2, "nombreFichero");
            return (Criteria) this;
        }

        public Criteria andExtensionIsNull() {
            addCriterion("EXTENSION is null");
            return (Criteria) this;
        }

        public Criteria andExtensionIsNotNull() {
            addCriterion("EXTENSION is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionEqualTo(String value) {
            addCriterion("EXTENSION =", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotEqualTo(String value) {
            addCriterion("EXTENSION <>", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionGreaterThan(String value) {
            addCriterion("EXTENSION >", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionGreaterThanOrEqualTo(String value) {
            addCriterion("EXTENSION >=", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionLessThan(String value) {
            addCriterion("EXTENSION <", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionLessThanOrEqualTo(String value) {
            addCriterion("EXTENSION <=", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionLike(String value) {
            addCriterion("EXTENSION like", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotLike(String value) {
            addCriterion("EXTENSION not like", value, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionIn(List<String> values) {
            addCriterion("EXTENSION in", values, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotIn(List<String> values) {
            addCriterion("EXTENSION not in", values, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionBetween(String value1, String value2) {
            addCriterion("EXTENSION between", value1, value2, "extension");
            return (Criteria) this;
        }

        public Criteria andExtensionNotBetween(String value1, String value2) {
            addCriterion("EXTENSION not between", value1, value2, "extension");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionIsNull() {
            addCriterion("DESCRIPCION_TIPO_OPERACION is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionIsNotNull() {
            addCriterion("DESCRIPCION_TIPO_OPERACION is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION =", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionNotEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION <>", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionGreaterThan(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION >", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION >=", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionLessThan(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION <", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION <=", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionLike(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION like", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionNotLike(String value) {
            addCriterion("DESCRIPCION_TIPO_OPERACION not like", value, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionIn(List<String> values) {
            addCriterion("DESCRIPCION_TIPO_OPERACION in", values, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionNotIn(List<String> values) {
            addCriterion("DESCRIPCION_TIPO_OPERACION not in", values, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_TIPO_OPERACION between", value1, value2, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoOperacionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_TIPO_OPERACION not between", value1, value2, "descripcionTipoOperacion");
            return (Criteria) this;
        }

        public Criteria andIdContratoIsNull() {
            addCriterion("ID_CONTRATO is null");
            return (Criteria) this;
        }

        public Criteria andIdContratoIsNotNull() {
            addCriterion("ID_CONTRATO is not null");
            return (Criteria) this;
        }

        public Criteria andIdContratoEqualTo(BigDecimal value) {
            addCriterion("ID_CONTRATO =", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotEqualTo(BigDecimal value) {
            addCriterion("ID_CONTRATO <>", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoGreaterThan(BigDecimal value) {
            addCriterion("ID_CONTRATO >", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_CONTRATO >=", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoLessThan(BigDecimal value) {
            addCriterion("ID_CONTRATO <", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_CONTRATO <=", value, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoIn(List<BigDecimal> values) {
            addCriterion("ID_CONTRATO in", values, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotIn(List<BigDecimal> values) {
            addCriterion("ID_CONTRATO not in", values, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_CONTRATO between", value1, value2, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdContratoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_CONTRATO not between", value1, value2, "idContrato");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteIsNull() {
            addCriterion("ID_EXPEDIENTE is null");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteIsNotNull() {
            addCriterion("ID_EXPEDIENTE is not null");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteEqualTo(BigDecimal value) {
            addCriterion("ID_EXPEDIENTE =", value, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteNotEqualTo(BigDecimal value) {
            addCriterion("ID_EXPEDIENTE <>", value, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteGreaterThan(BigDecimal value) {
            addCriterion("ID_EXPEDIENTE >", value, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_EXPEDIENTE >=", value, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteLessThan(BigDecimal value) {
            addCriterion("ID_EXPEDIENTE <", value, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_EXPEDIENTE <=", value, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteIn(List<BigDecimal> values) {
            addCriterion("ID_EXPEDIENTE in", values, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteNotIn(List<BigDecimal> values) {
            addCriterion("ID_EXPEDIENTE not in", values, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_EXPEDIENTE between", value1, value2, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andIdExpedienteNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_EXPEDIENTE not between", value1, value2, "idExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteIsNull() {
            addCriterion("CODIGO_EXPEDIENTE is null");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteIsNotNull() {
            addCriterion("CODIGO_EXPEDIENTE is not null");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteEqualTo(String value) {
            addCriterion("CODIGO_EXPEDIENTE =", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteNotEqualTo(String value) {
            addCriterion("CODIGO_EXPEDIENTE <>", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteGreaterThan(String value) {
            addCriterion("CODIGO_EXPEDIENTE >", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteGreaterThanOrEqualTo(String value) {
            addCriterion("CODIGO_EXPEDIENTE >=", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteLessThan(String value) {
            addCriterion("CODIGO_EXPEDIENTE <", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteLessThanOrEqualTo(String value) {
            addCriterion("CODIGO_EXPEDIENTE <=", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteLike(String value) {
            addCriterion("CODIGO_EXPEDIENTE like", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteNotLike(String value) {
            addCriterion("CODIGO_EXPEDIENTE not like", value, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteIn(List<String> values) {
            addCriterion("CODIGO_EXPEDIENTE in", values, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteNotIn(List<String> values) {
            addCriterion("CODIGO_EXPEDIENTE not in", values, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteBetween(String value1, String value2) {
            addCriterion("CODIGO_EXPEDIENTE between", value1, value2, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andCodigoExpedienteNotBetween(String value1, String value2) {
            addCriterion("CODIGO_EXPEDIENTE not between", value1, value2, "codigoExpediente");
            return (Criteria) this;
        }

        public Criteria andIdEntidadIsNull() {
            addCriterion("ID_ENTIDAD is null");
            return (Criteria) this;
        }

        public Criteria andIdEntidadIsNotNull() {
            addCriterion("ID_ENTIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andIdEntidadEqualTo(BigDecimal value) {
            addCriterion("ID_ENTIDAD =", value, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadNotEqualTo(BigDecimal value) {
            addCriterion("ID_ENTIDAD <>", value, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadGreaterThan(BigDecimal value) {
            addCriterion("ID_ENTIDAD >", value, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_ENTIDAD >=", value, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadLessThan(BigDecimal value) {
            addCriterion("ID_ENTIDAD <", value, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_ENTIDAD <=", value, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadIn(List<BigDecimal> values) {
            addCriterion("ID_ENTIDAD in", values, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadNotIn(List<BigDecimal> values) {
            addCriterion("ID_ENTIDAD not in", values, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_ENTIDAD between", value1, value2, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andIdEntidadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_ENTIDAD not between", value1, value2, "idEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadIsNull() {
            addCriterion("NOMBRE_ENTIDAD is null");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadIsNotNull() {
            addCriterion("NOMBRE_ENTIDAD is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadEqualTo(String value) {
            addCriterion("NOMBRE_ENTIDAD =", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadNotEqualTo(String value) {
            addCriterion("NOMBRE_ENTIDAD <>", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadGreaterThan(String value) {
            addCriterion("NOMBRE_ENTIDAD >", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadGreaterThanOrEqualTo(String value) {
            addCriterion("NOMBRE_ENTIDAD >=", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadLessThan(String value) {
            addCriterion("NOMBRE_ENTIDAD <", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadLessThanOrEqualTo(String value) {
            addCriterion("NOMBRE_ENTIDAD <=", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadLike(String value) {
            addCriterion("NOMBRE_ENTIDAD like", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadNotLike(String value) {
            addCriterion("NOMBRE_ENTIDAD not like", value, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadIn(List<String> values) {
            addCriterion("NOMBRE_ENTIDAD in", values, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadNotIn(List<String> values) {
            addCriterion("NOMBRE_ENTIDAD not in", values, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadBetween(String value1, String value2) {
            addCriterion("NOMBRE_ENTIDAD between", value1, value2, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andNombreEntidadNotBetween(String value1, String value2) {
            addCriterion("NOMBRE_ENTIDAD not between", value1, value2, "nombreEntidad");
            return (Criteria) this;
        }

        public Criteria andCifIsNull() {
            addCriterion("CIF is null");
            return (Criteria) this;
        }

        public Criteria andCifIsNotNull() {
            addCriterion("CIF is not null");
            return (Criteria) this;
        }

        public Criteria andCifEqualTo(String value) {
            addCriterion("CIF =", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifNotEqualTo(String value) {
            addCriterion("CIF <>", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifGreaterThan(String value) {
            addCriterion("CIF >", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifGreaterThanOrEqualTo(String value) {
            addCriterion("CIF >=", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifLessThan(String value) {
            addCriterion("CIF <", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifLessThanOrEqualTo(String value) {
            addCriterion("CIF <=", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifLike(String value) {
            addCriterion("CIF like", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifNotLike(String value) {
            addCriterion("CIF not like", value, "cif");
            return (Criteria) this;
        }

        public Criteria andCifIn(List<String> values) {
            addCriterion("CIF in", values, "cif");
            return (Criteria) this;
        }

        public Criteria andCifNotIn(List<String> values) {
            addCriterion("CIF not in", values, "cif");
            return (Criteria) this;
        }

        public Criteria andCifBetween(String value1, String value2) {
            addCriterion("CIF between", value1, value2, "cif");
            return (Criteria) this;
        }

        public Criteria andCifNotBetween(String value1, String value2) {
            addCriterion("CIF not between", value1, value2, "cif");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionIsNull() {
            addCriterion("ID_UNIDAD_CONTRATACION is null");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionIsNotNull() {
            addCriterion("ID_UNIDAD_CONTRATACION is not null");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionEqualTo(BigDecimal value) {
            addCriterion("ID_UNIDAD_CONTRATACION =", value, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionNotEqualTo(BigDecimal value) {
            addCriterion("ID_UNIDAD_CONTRATACION <>", value, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionGreaterThan(BigDecimal value) {
            addCriterion("ID_UNIDAD_CONTRATACION >", value, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_UNIDAD_CONTRATACION >=", value, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionLessThan(BigDecimal value) {
            addCriterion("ID_UNIDAD_CONTRATACION <", value, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_UNIDAD_CONTRATACION <=", value, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionIn(List<BigDecimal> values) {
            addCriterion("ID_UNIDAD_CONTRATACION in", values, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionNotIn(List<BigDecimal> values) {
            addCriterion("ID_UNIDAD_CONTRATACION not in", values, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_UNIDAD_CONTRATACION between", value1, value2, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andIdUnidadContratacionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_UNIDAD_CONTRATACION not between", value1, value2, "idUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionIsNull() {
            addCriterion("DESC_UNIDAD_CONTRATACION is null");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionIsNotNull() {
            addCriterion("DESC_UNIDAD_CONTRATACION is not null");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionEqualTo(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION =", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionNotEqualTo(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION <>", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionGreaterThan(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION >", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionGreaterThanOrEqualTo(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION >=", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionLessThan(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION <", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionLessThanOrEqualTo(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION <=", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionLike(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION like", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionNotLike(String value) {
            addCriterion("DESC_UNIDAD_CONTRATACION not like", value, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionIn(List<String> values) {
            addCriterion("DESC_UNIDAD_CONTRATACION in", values, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionNotIn(List<String> values) {
            addCriterion("DESC_UNIDAD_CONTRATACION not in", values, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionBetween(String value1, String value2) {
            addCriterion("DESC_UNIDAD_CONTRATACION between", value1, value2, "descUnidadContratacion");
            return (Criteria) this;
        }

        public Criteria andDescUnidadContratacionNotBetween(String value1, String value2) {
            addCriterion("DESC_UNIDAD_CONTRATACION not between", value1, value2, "descUnidadContratacion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 08 11:50:56 CEST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_ESDOCUMENTOS_V
     *
     * @mbggenerated Fri Jul 08 11:50:56 CEST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}