package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.Date;

public class ESDocumento {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_TO_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private BigDecimal idTipoOperacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_CON_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private BigDecimal idContrato;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_EN_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private BigDecimal idEntidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_OU_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private BigDecimal idOtrasUnidades;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_DESCRIPCION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_FECHA
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_TIPO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String tipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_ARIES
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String aries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_NOMBRE_FICHERO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String nombreFichero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_EXTENSION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_UC_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private BigDecimal idUnidadContratacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_F_ACTU
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private Date fActu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_U_ACTU
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String uActu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_F_CREACION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private Date fCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_U_CREACION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private String uCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ES_DOCUMENTOS.ES_FICHERO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    private byte[] fichero;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_ID
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_ID
     *
     * @param id the value for AJ_ES_DOCUMENTOS.ES_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_TO_ID
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_TO_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public BigDecimal getIdTipoOperacion() {
        return idTipoOperacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_TO_ID
     *
     * @param idTipoOperacion the value for AJ_ES_DOCUMENTOS.ES_TO_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setIdTipoOperacion(BigDecimal idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_CON_ID
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_CON_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public BigDecimal getIdContrato() {
        return idContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_CON_ID
     *
     * @param idContrato the value for AJ_ES_DOCUMENTOS.ES_CON_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setIdContrato(BigDecimal idContrato) {
        this.idContrato = idContrato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_EN_ID
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_EN_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public BigDecimal getIdEntidad() {
        return idEntidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_EN_ID
     *
     * @param idEntidad the value for AJ_ES_DOCUMENTOS.ES_EN_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setIdEntidad(BigDecimal idEntidad) {
        this.idEntidad = idEntidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_OU_ID
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_OU_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public BigDecimal getIdOtrasUnidades() {
        return idOtrasUnidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_OU_ID
     *
     * @param idOtrasUnidades the value for AJ_ES_DOCUMENTOS.ES_OU_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setIdOtrasUnidades(BigDecimal idOtrasUnidades) {
        this.idOtrasUnidades = idOtrasUnidades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_DESCRIPCION
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_DESCRIPCION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_DESCRIPCION
     *
     * @param descripcion the value for AJ_ES_DOCUMENTOS.ES_DESCRIPCION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_FECHA
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_FECHA
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_FECHA
     *
     * @param fecha the value for AJ_ES_DOCUMENTOS.ES_FECHA
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_TIPO
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_TIPO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_TIPO
     *
     * @param tipo the value for AJ_ES_DOCUMENTOS.ES_TIPO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setTipo(String tipo) {
        this.tipo = tipo == null ? null : tipo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_ARIES
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_ARIES
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getAries() {
        return aries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_ARIES
     *
     * @param aries the value for AJ_ES_DOCUMENTOS.ES_ARIES
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setAries(String aries) {
        this.aries = aries == null ? null : aries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_NOMBRE_FICHERO
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_NOMBRE_FICHERO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getNombreFichero() {
        return nombreFichero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_NOMBRE_FICHERO
     *
     * @param nombreFichero the value for AJ_ES_DOCUMENTOS.ES_NOMBRE_FICHERO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setNombreFichero(String nombreFichero) {
        this.nombreFichero = nombreFichero == null ? null : nombreFichero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_EXTENSION
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_EXTENSION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_EXTENSION
     *
     * @param extension the value for AJ_ES_DOCUMENTOS.ES_EXTENSION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_UC_ID
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_UC_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public BigDecimal getIdUnidadContratacion() {
        return idUnidadContratacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_UC_ID
     *
     * @param idUnidadContratacion the value for AJ_ES_DOCUMENTOS.ES_UC_ID
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setIdUnidadContratacion(BigDecimal idUnidadContratacion) {
        this.idUnidadContratacion = idUnidadContratacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_F_ACTU
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_F_ACTU
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public Date getfActu() {
        return fActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_F_ACTU
     *
     * @param fActu the value for AJ_ES_DOCUMENTOS.ES_F_ACTU
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setfActu(Date fActu) {
        this.fActu = fActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_U_ACTU
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_U_ACTU
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getuActu() {
        return uActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_U_ACTU
     *
     * @param uActu the value for AJ_ES_DOCUMENTOS.ES_U_ACTU
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setuActu(String uActu) {
        this.uActu = uActu == null ? null : uActu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_F_CREACION
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_F_CREACION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public Date getfCreacion() {
        return fCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_F_CREACION
     *
     * @param fCreacion the value for AJ_ES_DOCUMENTOS.ES_F_CREACION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setfCreacion(Date fCreacion) {
        this.fCreacion = fCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_U_CREACION
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_U_CREACION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public String getuCreacion() {
        return uCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_U_CREACION
     *
     * @param uCreacion the value for AJ_ES_DOCUMENTOS.ES_U_CREACION
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setuCreacion(String uCreacion) {
        this.uCreacion = uCreacion == null ? null : uCreacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ES_DOCUMENTOS.ES_FICHERO
     *
     * @return the value of AJ_ES_DOCUMENTOS.ES_FICHERO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public byte[] getFichero() {
        return fichero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ES_DOCUMENTOS.ES_FICHERO
     *
     * @param fichero the value for AJ_ES_DOCUMENTOS.ES_FICHERO
     *
     * @mbggenerated Fri Jul 08 12:37:49 CEST 2011
     */
    public void setFichero(byte[] fichero) {
        this.fichero = fichero;
    }

    public void setActualizacion(Date fecha, Usuario usuario) {
        this.fActu = fecha;
        this.uActu = usuario.getIdentificador();
    }

    public void setCreacion(Date fecha, Usuario usuario) {
        this.fCreacion = fecha;
        this.uCreacion = usuario.getIdentificador();
        this.fActu = fecha;
        this.uActu = usuario.getIdentificador();
    }

    public void copyCreacion(ESDocumento source) {
        this.fCreacion = source.fCreacion;
        this.uCreacion = source.uCreacion;
        this.fActu = source.fActu;
        this.uActu = source.uActu;
    }

    public void copyActualizacion(ESDocumento source) {
        this.fActu = source.fActu;
        this.uActu = source.uActu;
    }
}