package es.ise.ciceron.model;

import java.math.BigDecimal;

public class FirmantesInformes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_FIRMANTES_INFORMES_V.ID_UNIDAD_CONTRACION
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    private BigDecimal idUnidadContracion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_FIRMANTES_INFORMES_V.NOMBRE
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_FIRMANTES_INFORMES_V.DNI
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    private String dni;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_FIRMANTES_INFORMES_V.ID_UNIDAD_CONTRACION
     *
     * @return the value of AJ_FIRMANTES_INFORMES_V.ID_UNIDAD_CONTRACION
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    public BigDecimal getIdUnidadContracion() {
        return idUnidadContracion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_FIRMANTES_INFORMES_V.ID_UNIDAD_CONTRACION
     *
     * @param idUnidadContracion the value for AJ_FIRMANTES_INFORMES_V.ID_UNIDAD_CONTRACION
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    public void setIdUnidadContracion(BigDecimal idUnidadContracion) {
        this.idUnidadContracion = idUnidadContracion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_FIRMANTES_INFORMES_V.NOMBRE
     *
     * @return the value of AJ_FIRMANTES_INFORMES_V.NOMBRE
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_FIRMANTES_INFORMES_V.NOMBRE
     *
     * @param nombre the value for AJ_FIRMANTES_INFORMES_V.NOMBRE
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_FIRMANTES_INFORMES_V.DNI
     *
     * @return the value of AJ_FIRMANTES_INFORMES_V.DNI
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_FIRMANTES_INFORMES_V.DNI
     *
     * @param dni the value for AJ_FIRMANTES_INFORMES_V.DNI
     *
     * @mbggenerated Fri Jun 17 10:04:26 CEST 2011
     */
    public void setDni(String dni) {
        this.dni = dni == null ? null : dni.trim();
    }
}