package es.ise.ciceron.model;

import java.math.BigDecimal;

public class ParametrosSolicitudes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_NOMBRE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_LONGITUD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_TIPO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal idTipo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String lvSelect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_SOLICITUD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal idSolicitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_VALOR_DEFECTO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String valorDefecto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_PARAM_REPORT
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String paramReport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_VISTO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String visto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_OBLIGATORIO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String obligatorio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_ORDEN
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal orden;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT_WEB
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String lvSelectWeb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_ENTIDAD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String lEntidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_EXPEDIENTE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String lExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_CENTRO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String lCentro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_ID
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_ID
     *
     * @param id the value for CONTA.PARAMETROS_SOLICITUDES.PS_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_NOMBRE
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_NOMBRE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_NOMBRE
     *
     * @param nombre the value for CONTA.PARAMETROS_SOLICITUDES.PS_NOMBRE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_LONGITUD
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_LONGITUD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_LONGITUD
     *
     * @param longitud the value for CONTA.PARAMETROS_SOLICITUDES.PS_LONGITUD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_TIPO
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_TIPO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getIdTipo() {
        return idTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_TIPO
     *
     * @param idTipo the value for CONTA.PARAMETROS_SOLICITUDES.PS_TIPO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setIdTipo(BigDecimal idTipo) {
        this.idTipo = idTipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getLvSelect() {
        return lvSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT
     *
     * @param lvSelect the value for CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setLvSelect(String lvSelect) {
        this.lvSelect = lvSelect == null ? null : lvSelect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_SOLICITUD
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_SOLICITUD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getIdSolicitud() {
        return idSolicitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_SOLICITUD
     *
     * @param idSolicitud the value for CONTA.PARAMETROS_SOLICITUDES.PS_SOLICITUD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setIdSolicitud(BigDecimal idSolicitud) {
        this.idSolicitud = idSolicitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_VALOR_DEFECTO
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_VALOR_DEFECTO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getValorDefecto() {
        return valorDefecto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_VALOR_DEFECTO
     *
     * @param valorDefecto the value for CONTA.PARAMETROS_SOLICITUDES.PS_VALOR_DEFECTO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setValorDefecto(String valorDefecto) {
        this.valorDefecto = valorDefecto == null ? null : valorDefecto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_PARAM_REPORT
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_PARAM_REPORT
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getParamReport() {
        return paramReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_PARAM_REPORT
     *
     * @param paramReport the value for CONTA.PARAMETROS_SOLICITUDES.PS_PARAM_REPORT
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setParamReport(String paramReport) {
        this.paramReport = paramReport == null ? null : paramReport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_VISTO
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_VISTO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getVisto() {
        return visto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_VISTO
     *
     * @param visto the value for CONTA.PARAMETROS_SOLICITUDES.PS_VISTO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setVisto(String visto) {
        this.visto = visto == null ? null : visto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_OBLIGATORIO
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_OBLIGATORIO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getObligatorio() {
        return obligatorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_OBLIGATORIO
     *
     * @param obligatorio the value for CONTA.PARAMETROS_SOLICITUDES.PS_OBLIGATORIO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setObligatorio(String obligatorio) {
        this.obligatorio = obligatorio == null ? null : obligatorio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_ORDEN
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_ORDEN
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getOrden() {
        return orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_ORDEN
     *
     * @param orden the value for CONTA.PARAMETROS_SOLICITUDES.PS_ORDEN
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setOrden(BigDecimal orden) {
        this.orden = orden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT_WEB
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT_WEB
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getLvSelectWeb() {
        return lvSelectWeb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT_WEB
     *
     * @param lvSelectWeb the value for CONTA.PARAMETROS_SOLICITUDES.PS_LV_SELECT_WEB
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setLvSelectWeb(String lvSelectWeb) {
        this.lvSelectWeb = lvSelectWeb == null ? null : lvSelectWeb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_ENTIDAD
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_L_ENTIDAD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getlEntidad() {
        return lEntidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_ENTIDAD
     *
     * @param lEntidad the value for CONTA.PARAMETROS_SOLICITUDES.PS_L_ENTIDAD
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setlEntidad(String lEntidad) {
        this.lEntidad = lEntidad == null ? null : lEntidad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_EXPEDIENTE
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_L_EXPEDIENTE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getlExpediente() {
        return lExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_EXPEDIENTE
     *
     * @param lExpediente the value for CONTA.PARAMETROS_SOLICITUDES.PS_L_EXPEDIENTE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setlExpediente(String lExpediente) {
        this.lExpediente = lExpediente == null ? null : lExpediente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_CENTRO
     *
     * @return the value of CONTA.PARAMETROS_SOLICITUDES.PS_L_CENTRO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getlCentro() {
        return lCentro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTA.PARAMETROS_SOLICITUDES.PS_L_CENTRO
     *
     * @param lCentro the value for CONTA.PARAMETROS_SOLICITUDES.PS_L_CENTRO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setlCentro(String lCentro) {
        this.lCentro = lCentro == null ? null : lCentro.trim();
    }
}