package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PuntoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public PuntoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("P_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("P_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("P_ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("P_ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("P_ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("P_ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("P_ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("P_ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("P_ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("P_ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdBloqueIsNull() {
            addCriterion("P_B_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdBloqueIsNotNull() {
            addCriterion("P_B_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdBloqueEqualTo(BigDecimal value) {
            addCriterion("P_B_ID =", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueNotEqualTo(BigDecimal value) {
            addCriterion("P_B_ID <>", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueGreaterThan(BigDecimal value) {
            addCriterion("P_B_ID >", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("P_B_ID >=", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueLessThan(BigDecimal value) {
            addCriterion("P_B_ID <", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("P_B_ID <=", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueIn(List<BigDecimal> values) {
            addCriterion("P_B_ID in", values, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueNotIn(List<BigDecimal> values) {
            addCriterion("P_B_ID not in", values, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_B_ID between", value1, value2, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_B_ID not between", value1, value2, "idBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaIsNull() {
            addCriterion("P_DESCRIPCION_CORTA is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaIsNotNull() {
            addCriterion("P_DESCRIPCION_CORTA is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaEqualTo(String value) {
            addCriterion("P_DESCRIPCION_CORTA =", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotEqualTo(String value) {
            addCriterion("P_DESCRIPCION_CORTA <>", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaGreaterThan(String value) {
            addCriterion("P_DESCRIPCION_CORTA >", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaGreaterThanOrEqualTo(String value) {
            addCriterion("P_DESCRIPCION_CORTA >=", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaLessThan(String value) {
            addCriterion("P_DESCRIPCION_CORTA <", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaLessThanOrEqualTo(String value) {
            addCriterion("P_DESCRIPCION_CORTA <=", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaLike(String value) {
            addCriterion("P_DESCRIPCION_CORTA like", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotLike(String value) {
            addCriterion("P_DESCRIPCION_CORTA not like", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaIn(List<String> values) {
            addCriterion("P_DESCRIPCION_CORTA in", values, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotIn(List<String> values) {
            addCriterion("P_DESCRIPCION_CORTA not in", values, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaBetween(String value1, String value2) {
            addCriterion("P_DESCRIPCION_CORTA between", value1, value2, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotBetween(String value1, String value2) {
            addCriterion("P_DESCRIPCION_CORTA not between", value1, value2, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaIsNull() {
            addCriterion("P_DESCRIPCION_LARGA is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaIsNotNull() {
            addCriterion("P_DESCRIPCION_LARGA is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaEqualTo(String value) {
            addCriterion("P_DESCRIPCION_LARGA =", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotEqualTo(String value) {
            addCriterion("P_DESCRIPCION_LARGA <>", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaGreaterThan(String value) {
            addCriterion("P_DESCRIPCION_LARGA >", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaGreaterThanOrEqualTo(String value) {
            addCriterion("P_DESCRIPCION_LARGA >=", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaLessThan(String value) {
            addCriterion("P_DESCRIPCION_LARGA <", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaLessThanOrEqualTo(String value) {
            addCriterion("P_DESCRIPCION_LARGA <=", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaLike(String value) {
            addCriterion("P_DESCRIPCION_LARGA like", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotLike(String value) {
            addCriterion("P_DESCRIPCION_LARGA not like", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaIn(List<String> values) {
            addCriterion("P_DESCRIPCION_LARGA in", values, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotIn(List<String> values) {
            addCriterion("P_DESCRIPCION_LARGA not in", values, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaBetween(String value1, String value2) {
            addCriterion("P_DESCRIPCION_LARGA between", value1, value2, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotBetween(String value1, String value2) {
            addCriterion("P_DESCRIPCION_LARGA not between", value1, value2, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNull() {
            addCriterion("P_ORDEN is null");
            return (Criteria) this;
        }

        public Criteria andOrdenIsNotNull() {
            addCriterion("P_ORDEN is not null");
            return (Criteria) this;
        }

        public Criteria andOrdenEqualTo(BigDecimal value) {
            addCriterion("P_ORDEN =", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotEqualTo(BigDecimal value) {
            addCriterion("P_ORDEN <>", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThan(BigDecimal value) {
            addCriterion("P_ORDEN >", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("P_ORDEN >=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThan(BigDecimal value) {
            addCriterion("P_ORDEN <", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenLessThanOrEqualTo(BigDecimal value) {
            addCriterion("P_ORDEN <=", value, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenIn(List<BigDecimal> values) {
            addCriterion("P_ORDEN in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotIn(List<BigDecimal> values) {
            addCriterion("P_ORDEN not in", values, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_ORDEN between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andOrdenNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("P_ORDEN not between", value1, value2, "orden");
            return (Criteria) this;
        }

        public Criteria andUCreacionIsNull() {
            addCriterion("P_U_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andUCreacionIsNotNull() {
            addCriterion("P_U_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andUCreacionEqualTo(String value) {
            addCriterion("P_U_CREACION =", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotEqualTo(String value) {
            addCriterion("P_U_CREACION <>", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionGreaterThan(String value) {
            addCriterion("P_U_CREACION >", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionGreaterThanOrEqualTo(String value) {
            addCriterion("P_U_CREACION >=", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionLessThan(String value) {
            addCriterion("P_U_CREACION <", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionLessThanOrEqualTo(String value) {
            addCriterion("P_U_CREACION <=", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionLike(String value) {
            addCriterion("P_U_CREACION like", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotLike(String value) {
            addCriterion("P_U_CREACION not like", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionIn(List<String> values) {
            addCriterion("P_U_CREACION in", values, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotIn(List<String> values) {
            addCriterion("P_U_CREACION not in", values, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionBetween(String value1, String value2) {
            addCriterion("P_U_CREACION between", value1, value2, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotBetween(String value1, String value2) {
            addCriterion("P_U_CREACION not between", value1, value2, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionIsNull() {
            addCriterion("P_F_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andFCreacionIsNotNull() {
            addCriterion("P_F_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andFCreacionEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_CREACION =", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionNotEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_CREACION <>", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionGreaterThan(Date value) {
            addCriterionForJDBCDate("P_F_CREACION >", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_CREACION >=", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionLessThan(Date value) {
            addCriterionForJDBCDate("P_F_CREACION <", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_CREACION <=", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionIn(List<Date> values) {
            addCriterionForJDBCDate("P_F_CREACION in", values, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionNotIn(List<Date> values) {
            addCriterionForJDBCDate("P_F_CREACION not in", values, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("P_F_CREACION between", value1, value2, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("P_F_CREACION not between", value1, value2, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andUActuIsNull() {
            addCriterion("P_U_ACTU is null");
            return (Criteria) this;
        }

        public Criteria andUActuIsNotNull() {
            addCriterion("P_U_ACTU is not null");
            return (Criteria) this;
        }

        public Criteria andUActuEqualTo(String value) {
            addCriterion("P_U_ACTU =", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotEqualTo(String value) {
            addCriterion("P_U_ACTU <>", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuGreaterThan(String value) {
            addCriterion("P_U_ACTU >", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuGreaterThanOrEqualTo(String value) {
            addCriterion("P_U_ACTU >=", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuLessThan(String value) {
            addCriterion("P_U_ACTU <", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuLessThanOrEqualTo(String value) {
            addCriterion("P_U_ACTU <=", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuLike(String value) {
            addCriterion("P_U_ACTU like", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotLike(String value) {
            addCriterion("P_U_ACTU not like", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuIn(List<String> values) {
            addCriterion("P_U_ACTU in", values, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotIn(List<String> values) {
            addCriterion("P_U_ACTU not in", values, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuBetween(String value1, String value2) {
            addCriterion("P_U_ACTU between", value1, value2, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotBetween(String value1, String value2) {
            addCriterion("P_U_ACTU not between", value1, value2, "uActu");
            return (Criteria) this;
        }

        public Criteria andFActuIsNull() {
            addCriterion("P_F_ACTU is null");
            return (Criteria) this;
        }

        public Criteria andFActuIsNotNull() {
            addCriterion("P_F_ACTU is not null");
            return (Criteria) this;
        }

        public Criteria andFActuEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_ACTU =", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuNotEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_ACTU <>", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuGreaterThan(Date value) {
            addCriterionForJDBCDate("P_F_ACTU >", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_ACTU >=", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuLessThan(Date value) {
            addCriterionForJDBCDate("P_F_ACTU <", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("P_F_ACTU <=", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuIn(List<Date> values) {
            addCriterionForJDBCDate("P_F_ACTU in", values, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuNotIn(List<Date> values) {
            addCriterionForJDBCDate("P_F_ACTU not in", values, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("P_F_ACTU between", value1, value2, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("P_F_ACTU not between", value1, value2, "fActu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 08 10:45:32 CEST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_PUNTOS
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}