package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TipoBloquePuntosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public TipoBloquePuntosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdTipoIsNull() {
            addCriterion("ID_TIPO is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoIsNotNull() {
            addCriterion("ID_TIPO is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO =", value, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoNotEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO <>", value, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoGreaterThan(BigDecimal value) {
            addCriterion("ID_TIPO >", value, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO >=", value, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoLessThan(BigDecimal value) {
            addCriterion("ID_TIPO <", value, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_TIPO <=", value, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoIn(List<BigDecimal> values) {
            addCriterion("ID_TIPO in", values, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoNotIn(List<BigDecimal> values) {
            addCriterion("ID_TIPO not in", values, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_TIPO between", value1, value2, "idTipo");
            return (Criteria) this;
        }

        public Criteria andIdTipoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_TIPO not between", value1, value2, "idTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoIsNull() {
            addCriterion("DESCRIPCION_TIPO is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoIsNotNull() {
            addCriterion("DESCRIPCION_TIPO is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO =", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoNotEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO <>", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoGreaterThan(String value) {
            addCriterion("DESCRIPCION_TIPO >", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO >=", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoLessThan(String value) {
            addCriterion("DESCRIPCION_TIPO <", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_TIPO <=", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoLike(String value) {
            addCriterion("DESCRIPCION_TIPO like", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoNotLike(String value) {
            addCriterion("DESCRIPCION_TIPO not like", value, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoIn(List<String> values) {
            addCriterion("DESCRIPCION_TIPO in", values, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoNotIn(List<String> values) {
            addCriterion("DESCRIPCION_TIPO not in", values, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_TIPO between", value1, value2, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andDescripcionTipoNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_TIPO not between", value1, value2, "descripcionTipo");
            return (Criteria) this;
        }

        public Criteria andIdBloqueIsNull() {
            addCriterion("ID_BLOQUE is null");
            return (Criteria) this;
        }

        public Criteria andIdBloqueIsNotNull() {
            addCriterion("ID_BLOQUE is not null");
            return (Criteria) this;
        }

        public Criteria andIdBloqueEqualTo(BigDecimal value) {
            addCriterion("ID_BLOQUE =", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueNotEqualTo(BigDecimal value) {
            addCriterion("ID_BLOQUE <>", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueGreaterThan(BigDecimal value) {
            addCriterion("ID_BLOQUE >", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_BLOQUE >=", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueLessThan(BigDecimal value) {
            addCriterion("ID_BLOQUE <", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_BLOQUE <=", value, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueIn(List<BigDecimal> values) {
            addCriterion("ID_BLOQUE in", values, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueNotIn(List<BigDecimal> values) {
            addCriterion("ID_BLOQUE not in", values, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_BLOQUE between", value1, value2, "idBloque");
            return (Criteria) this;
        }

        public Criteria andIdBloqueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_BLOQUE not between", value1, value2, "idBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueIsNull() {
            addCriterion("DESCRIPCION_BLOQUE is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueIsNotNull() {
            addCriterion("DESCRIPCION_BLOQUE is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueEqualTo(String value) {
            addCriterion("DESCRIPCION_BLOQUE =", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueNotEqualTo(String value) {
            addCriterion("DESCRIPCION_BLOQUE <>", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueGreaterThan(String value) {
            addCriterion("DESCRIPCION_BLOQUE >", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_BLOQUE >=", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueLessThan(String value) {
            addCriterion("DESCRIPCION_BLOQUE <", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_BLOQUE <=", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueLike(String value) {
            addCriterion("DESCRIPCION_BLOQUE like", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueNotLike(String value) {
            addCriterion("DESCRIPCION_BLOQUE not like", value, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueIn(List<String> values) {
            addCriterion("DESCRIPCION_BLOQUE in", values, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueNotIn(List<String> values) {
            addCriterion("DESCRIPCION_BLOQUE not in", values, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_BLOQUE between", value1, value2, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andDescripcionBloqueNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_BLOQUE not between", value1, value2, "descripcionBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueIsNull() {
            addCriterion("ORDEN_BLOQUE is null");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueIsNotNull() {
            addCriterion("ORDEN_BLOQUE is not null");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueEqualTo(BigDecimal value) {
            addCriterion("ORDEN_BLOQUE =", value, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueNotEqualTo(BigDecimal value) {
            addCriterion("ORDEN_BLOQUE <>", value, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueGreaterThan(BigDecimal value) {
            addCriterion("ORDEN_BLOQUE >", value, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDEN_BLOQUE >=", value, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueLessThan(BigDecimal value) {
            addCriterion("ORDEN_BLOQUE <", value, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDEN_BLOQUE <=", value, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueIn(List<BigDecimal> values) {
            addCriterion("ORDEN_BLOQUE in", values, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueNotIn(List<BigDecimal> values) {
            addCriterion("ORDEN_BLOQUE not in", values, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDEN_BLOQUE between", value1, value2, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andOrdenBloqueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDEN_BLOQUE not between", value1, value2, "ordenBloque");
            return (Criteria) this;
        }

        public Criteria andIdPuntoIsNull() {
            addCriterion("ID_PUNTO is null");
            return (Criteria) this;
        }

        public Criteria andIdPuntoIsNotNull() {
            addCriterion("ID_PUNTO is not null");
            return (Criteria) this;
        }

        public Criteria andIdPuntoEqualTo(BigDecimal value) {
            addCriterion("ID_PUNTO =", value, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoNotEqualTo(BigDecimal value) {
            addCriterion("ID_PUNTO <>", value, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoGreaterThan(BigDecimal value) {
            addCriterion("ID_PUNTO >", value, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PUNTO >=", value, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoLessThan(BigDecimal value) {
            addCriterion("ID_PUNTO <", value, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID_PUNTO <=", value, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoIn(List<BigDecimal> values) {
            addCriterion("ID_PUNTO in", values, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoNotIn(List<BigDecimal> values) {
            addCriterion("ID_PUNTO not in", values, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PUNTO between", value1, value2, "idPunto");
            return (Criteria) this;
        }

        public Criteria andIdPuntoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID_PUNTO not between", value1, value2, "idPunto");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaIsNull() {
            addCriterion("DESCRIPCION_CORTA is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaIsNotNull() {
            addCriterion("DESCRIPCION_CORTA is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaEqualTo(String value) {
            addCriterion("DESCRIPCION_CORTA =", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotEqualTo(String value) {
            addCriterion("DESCRIPCION_CORTA <>", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaGreaterThan(String value) {
            addCriterion("DESCRIPCION_CORTA >", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_CORTA >=", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaLessThan(String value) {
            addCriterion("DESCRIPCION_CORTA <", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_CORTA <=", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaLike(String value) {
            addCriterion("DESCRIPCION_CORTA like", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotLike(String value) {
            addCriterion("DESCRIPCION_CORTA not like", value, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaIn(List<String> values) {
            addCriterion("DESCRIPCION_CORTA in", values, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotIn(List<String> values) {
            addCriterion("DESCRIPCION_CORTA not in", values, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_CORTA between", value1, value2, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionCortaNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_CORTA not between", value1, value2, "descripcionCorta");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaIsNull() {
            addCriterion("DESCRIPCION_LARGA is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaIsNotNull() {
            addCriterion("DESCRIPCION_LARGA is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaEqualTo(String value) {
            addCriterion("DESCRIPCION_LARGA =", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotEqualTo(String value) {
            addCriterion("DESCRIPCION_LARGA <>", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaGreaterThan(String value) {
            addCriterion("DESCRIPCION_LARGA >", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_LARGA >=", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaLessThan(String value) {
            addCriterion("DESCRIPCION_LARGA <", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPCION_LARGA <=", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaLike(String value) {
            addCriterion("DESCRIPCION_LARGA like", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotLike(String value) {
            addCriterion("DESCRIPCION_LARGA not like", value, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaIn(List<String> values) {
            addCriterion("DESCRIPCION_LARGA in", values, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotIn(List<String> values) {
            addCriterion("DESCRIPCION_LARGA not in", values, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_LARGA between", value1, value2, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andDescripcionLargaNotBetween(String value1, String value2) {
            addCriterion("DESCRIPCION_LARGA not between", value1, value2, "descripcionLarga");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoIsNull() {
            addCriterion("ORDEN_PUNTO is null");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoIsNotNull() {
            addCriterion("ORDEN_PUNTO is not null");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoEqualTo(BigDecimal value) {
            addCriterion("ORDEN_PUNTO =", value, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoNotEqualTo(BigDecimal value) {
            addCriterion("ORDEN_PUNTO <>", value, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoGreaterThan(BigDecimal value) {
            addCriterion("ORDEN_PUNTO >", value, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDEN_PUNTO >=", value, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoLessThan(BigDecimal value) {
            addCriterion("ORDEN_PUNTO <", value, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDEN_PUNTO <=", value, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoIn(List<BigDecimal> values) {
            addCriterion("ORDEN_PUNTO in", values, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoNotIn(List<BigDecimal> values) {
            addCriterion("ORDEN_PUNTO not in", values, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDEN_PUNTO between", value1, value2, "ordenPunto");
            return (Criteria) this;
        }

        public Criteria andOrdenPuntoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDEN_PUNTO not between", value1, value2, "ordenPunto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 24 09:41:32 CEST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_TIPOBLOQUEPUNTOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}