package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.Date;

public class AccesoContratos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCESOS_CONTRATOS.ACC_ID
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCESOS_CONTRATOS.ACC_NIF_USUARIO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String nifUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCESOS_CONTRATOS.ACC_PAGINA_ENTRADA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String paginaEntrada;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCESOS_CONTRATOS.ACC_FECHA_CADUCIDAD
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private Date fechaCaducidad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCESOS_CONTRATOS.ACC_ID
     *
     * @return the value of ACCESOS_CONTRATOS.ACC_ID
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCESOS_CONTRATOS.ACC_ID
     *
     * @param id the value for ACCESOS_CONTRATOS.ACC_ID
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCESOS_CONTRATOS.ACC_NIF_USUARIO
     *
     * @return the value of ACCESOS_CONTRATOS.ACC_NIF_USUARIO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getNifUsuario() {
        return nifUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCESOS_CONTRATOS.ACC_NIF_USUARIO
     *
     * @param nifUsuario the value for ACCESOS_CONTRATOS.ACC_NIF_USUARIO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setNifUsuario(String nifUsuario) {
        this.nifUsuario = nifUsuario == null ? null : nifUsuario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCESOS_CONTRATOS.ACC_PAGINA_ENTRADA
     *
     * @return the value of ACCESOS_CONTRATOS.ACC_PAGINA_ENTRADA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getPaginaEntrada() {
        return paginaEntrada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCESOS_CONTRATOS.ACC_PAGINA_ENTRADA
     *
     * @param paginaEntrada the value for ACCESOS_CONTRATOS.ACC_PAGINA_ENTRADA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setPaginaEntrada(String paginaEntrada) {
        this.paginaEntrada = paginaEntrada == null ? null : paginaEntrada.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCESOS_CONTRATOS.ACC_FECHA_CADUCIDAD
     *
     * @return the value of ACCESOS_CONTRATOS.ACC_FECHA_CADUCIDAD
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public Date getFechaCaducidad() {
        return fechaCaducidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCESOS_CONTRATOS.ACC_FECHA_CADUCIDAD
     *
     * @param fechaCaducidad the value for ACCESOS_CONTRATOS.ACC_FECHA_CADUCIDAD
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
}