package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.Date;

public class Archivo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_ES_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private BigDecimal idArchivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_NOMBRE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_EXTENSION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_MIME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String mime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_U_ACTU
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String uActu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_U_CREACION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private String uCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_F_ACTU
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private Date fActu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_F_CREACION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private Date fCreacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_ARCHIVO.AR_ARCHIVO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    private byte[] archivo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_ID
     *
     * @return the value of AJ_ARCHIVO.AR_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_ID
     *
     * @param id the value for AJ_ARCHIVO.AR_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_ES_ID
     *
     * @return the value of AJ_ARCHIVO.AR_ES_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public BigDecimal getIdArchivo() {
        return idArchivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_ES_ID
     *
     * @param idArchivo the value for AJ_ARCHIVO.AR_ES_ID
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setIdArchivo(BigDecimal idArchivo) {
        this.idArchivo = idArchivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_NOMBRE
     *
     * @return the value of AJ_ARCHIVO.AR_NOMBRE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_NOMBRE
     *
     * @param nombre the value for AJ_ARCHIVO.AR_NOMBRE
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setNombre(String nombre) {
        this.nombre = nombre == null ? null : nombre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_EXTENSION
     *
     * @return the value of AJ_ARCHIVO.AR_EXTENSION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_EXTENSION
     *
     * @param extension the value for AJ_ARCHIVO.AR_EXTENSION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_MIME
     *
     * @return the value of AJ_ARCHIVO.AR_MIME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getMime() {
        return mime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_MIME
     *
     * @param mime the value for AJ_ARCHIVO.AR_MIME
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setMime(String mime) {
        this.mime = mime == null ? null : mime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_U_ACTU
     *
     * @return the value of AJ_ARCHIVO.AR_U_ACTU
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getuActu() {
        return uActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_U_ACTU
     *
     * @param uActu the value for AJ_ARCHIVO.AR_U_ACTU
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setuActu(String uActu) {
        this.uActu = uActu == null ? null : uActu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_U_CREACION
     *
     * @return the value of AJ_ARCHIVO.AR_U_CREACION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public String getuCreacion() {
        return uCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_U_CREACION
     *
     * @param uCreacion the value for AJ_ARCHIVO.AR_U_CREACION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setuCreacion(String uCreacion) {
        this.uCreacion = uCreacion == null ? null : uCreacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_F_ACTU
     *
     * @return the value of AJ_ARCHIVO.AR_F_ACTU
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public Date getfActu() {
        return fActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_F_ACTU
     *
     * @param fActu the value for AJ_ARCHIVO.AR_F_ACTU
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setfActu(Date fActu) {
        this.fActu = fActu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_F_CREACION
     *
     * @return the value of AJ_ARCHIVO.AR_F_CREACION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public Date getfCreacion() {
        return fCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_F_CREACION
     *
     * @param fCreacion the value for AJ_ARCHIVO.AR_F_CREACION
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setfCreacion(Date fCreacion) {
        this.fCreacion = fCreacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_ARCHIVO.AR_ARCHIVO
     *
     * @return the value of AJ_ARCHIVO.AR_ARCHIVO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public byte[] getArchivo() {
        return archivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_ARCHIVO.AR_ARCHIVO
     *
     * @param archivo the value for AJ_ARCHIVO.AR_ARCHIVO
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    public void setArchivo(byte[] archivo) {
        this.archivo = archivo;
    }

    public void setActualizacion(Date fecha, Usuario usuario) {
        this.fActu = fecha;
        this.uActu = usuario.getIdentificador();
    }

    public void setCreacion(Date fecha, Usuario usuario) {
        this.fCreacion = fecha;
        this.uCreacion = usuario.getIdentificador();
        this.fActu = fecha;
        this.uActu = usuario.getIdentificador();
    }

    public void copyCreacion(Archivo source) {
        this.fCreacion = source.fCreacion;
        this.uCreacion = source.uCreacion;
        this.fActu = source.fActu;
        this.uActu = source.uActu;
    }

    public void copyActualizacion(Archivo source) {
        this.fActu = source.fActu;
        this.uActu = source.uActu;
    }
}