package es.ise.ciceron.model;

import java.math.BigDecimal;

public class PuntosEditados {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ID_TEXTO_INFORME
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal idTextoInforme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ID_INFORME
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal idInforme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ID_EXPEDIENTE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal idExpediente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ORDEN_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal ordenPunto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String descripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String descripcionPunto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_BLOQUE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String descripcionBloque;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_TIPOLOGIA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String descripcionTipologia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.TEXTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private String texto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ID_TIPOLOGIA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal idTipologia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ID_BLOQUE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal idBloque;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AJ_PUNTOSEDITADOS_V.ID_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    private BigDecimal idPunto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ID_TEXTO_INFORME
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ID_TEXTO_INFORME
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getIdTextoInforme() {
        return idTextoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ID_TEXTO_INFORME
     *
     * @param idTextoInforme the value for AJ_PUNTOSEDITADOS_V.ID_TEXTO_INFORME
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setIdTextoInforme(BigDecimal idTextoInforme) {
        this.idTextoInforme = idTextoInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ID_INFORME
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ID_INFORME
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getIdInforme() {
        return idInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ID_INFORME
     *
     * @param idInforme the value for AJ_PUNTOSEDITADOS_V.ID_INFORME
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setIdInforme(BigDecimal idInforme) {
        this.idInforme = idInforme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ID_EXPEDIENTE
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ID_EXPEDIENTE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getIdExpediente() {
        return idExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ID_EXPEDIENTE
     *
     * @param idExpediente the value for AJ_PUNTOSEDITADOS_V.ID_EXPEDIENTE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setIdExpediente(BigDecimal idExpediente) {
        this.idExpediente = idExpediente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ORDEN_PUNTO
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ORDEN_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getOrdenPunto() {
        return ordenPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ORDEN_PUNTO
     *
     * @param ordenPunto the value for AJ_PUNTOSEDITADOS_V.ORDEN_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setOrdenPunto(BigDecimal ordenPunto) {
        this.ordenPunto = ordenPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION
     *
     * @param descripcion the value for AJ_PUNTOSEDITADOS_V.DESCRIPCION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion == null ? null : descripcion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_PUNTO
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.DESCRIPCION_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getDescripcionPunto() {
        return descripcionPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_PUNTO
     *
     * @param descripcionPunto the value for AJ_PUNTOSEDITADOS_V.DESCRIPCION_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setDescripcionPunto(String descripcionPunto) {
        this.descripcionPunto = descripcionPunto == null ? null : descripcionPunto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_BLOQUE
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.DESCRIPCION_BLOQUE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getDescripcionBloque() {
        return descripcionBloque;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_BLOQUE
     *
     * @param descripcionBloque the value for AJ_PUNTOSEDITADOS_V.DESCRIPCION_BLOQUE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setDescripcionBloque(String descripcionBloque) {
        this.descripcionBloque = descripcionBloque == null ? null : descripcionBloque.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_TIPOLOGIA
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.DESCRIPCION_TIPOLOGIA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getDescripcionTipologia() {
        return descripcionTipologia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.DESCRIPCION_TIPOLOGIA
     *
     * @param descripcionTipologia the value for AJ_PUNTOSEDITADOS_V.DESCRIPCION_TIPOLOGIA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setDescripcionTipologia(String descripcionTipologia) {
        this.descripcionTipologia = descripcionTipologia == null ? null : descripcionTipologia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.TEXTO
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.TEXTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public String getTexto() {
        return texto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.TEXTO
     *
     * @param texto the value for AJ_PUNTOSEDITADOS_V.TEXTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setTexto(String texto) {
        this.texto = texto == null ? null : texto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ID_TIPOLOGIA
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ID_TIPOLOGIA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getIdTipologia() {
        return idTipologia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ID_TIPOLOGIA
     *
     * @param idTipologia the value for AJ_PUNTOSEDITADOS_V.ID_TIPOLOGIA
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setIdTipologia(BigDecimal idTipologia) {
        this.idTipologia = idTipologia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ID_BLOQUE
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ID_BLOQUE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getIdBloque() {
        return idBloque;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ID_BLOQUE
     *
     * @param idBloque the value for AJ_PUNTOSEDITADOS_V.ID_BLOQUE
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setIdBloque(BigDecimal idBloque) {
        this.idBloque = idBloque;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AJ_PUNTOSEDITADOS_V.ID_PUNTO
     *
     * @return the value of AJ_PUNTOSEDITADOS_V.ID_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public BigDecimal getIdPunto() {
        return idPunto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AJ_PUNTOSEDITADOS_V.ID_PUNTO
     *
     * @param idPunto the value for AJ_PUNTOSEDITADOS_V.ID_PUNTO
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    public void setIdPunto(BigDecimal idPunto) {
        this.idPunto = idPunto;
    }
}