package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Modificados;
import es.ise.ciceron.model.ModificadosExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ModificadosMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int countByExample(ModificadosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int deleteByExample(ModificadosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int insert(Modificados record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int insertSelective(Modificados record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    List<Modificados> selectByExample(ModificadosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    Modificados selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int updateByExampleSelective(@Param("record") Modificados record, @Param("example") ModificadosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int updateByExample(@Param("record") Modificados record, @Param("example") ModificadosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int updateByPrimaryKeySelective(Modificados record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CON_MODIFICADOS
     *
     * @mbggenerated Wed Aug 24 13:36:43 CEST 2011
     */
    int updateByPrimaryKey(Modificados record);
}