package es.ise.ciceron.mapper;

import es.ise.ciceron.model.VersionesPliegos;
import es.ise.ciceron.model.VersionesPliegosExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface VersionesPliegosMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int countByExample(VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int deleteByExample(VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int insert(VersionesPliegos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int insertSelective(VersionesPliegos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<VersionesPliegos> selectByExampleWithBLOBs(VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<VersionesPliegos> selectByExample(VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    VersionesPliegos selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByExampleSelective(@Param("record") VersionesPliegos record, @Param("example") VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByExampleWithBLOBs(@Param("record") VersionesPliegos record, @Param("example") VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByExample(@Param("record") VersionesPliegos record, @Param("example") VersionesPliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByPrimaryKeySelective(VersionesPliegos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByPrimaryKeyWithBLOBs(VersionesPliegos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int updateByPrimaryKey(VersionesPliegos record);
}