package es.ise.ciceron.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ObservacionesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:14 CEST 2011
     */
    public ObservacionesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("OB_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("OB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("OB_ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("OB_ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("OB_ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OB_ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("OB_ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OB_ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("OB_ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("OB_ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OB_ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OB_ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTipoIsNull() {
            addCriterion("OB_TIPO is null");
            return (Criteria) this;
        }

        public Criteria andTipoIsNotNull() {
            addCriterion("OB_TIPO is not null");
            return (Criteria) this;
        }

        public Criteria andTipoEqualTo(String value) {
            addCriterion("OB_TIPO =", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotEqualTo(String value) {
            addCriterion("OB_TIPO <>", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThan(String value) {
            addCriterion("OB_TIPO >", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoGreaterThanOrEqualTo(String value) {
            addCriterion("OB_TIPO >=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThan(String value) {
            addCriterion("OB_TIPO <", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLessThanOrEqualTo(String value) {
            addCriterion("OB_TIPO <=", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoLike(String value) {
            addCriterion("OB_TIPO like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotLike(String value) {
            addCriterion("OB_TIPO not like", value, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoIn(List<String> values) {
            addCriterion("OB_TIPO in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotIn(List<String> values) {
            addCriterion("OB_TIPO not in", values, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoBetween(String value1, String value2) {
            addCriterion("OB_TIPO between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andTipoNotBetween(String value1, String value2) {
            addCriterion("OB_TIPO not between", value1, value2, "tipo");
            return (Criteria) this;
        }

        public Criteria andIdentIsNull() {
            addCriterion("OB_IDENT is null");
            return (Criteria) this;
        }

        public Criteria andIdentIsNotNull() {
            addCriterion("OB_IDENT is not null");
            return (Criteria) this;
        }

        public Criteria andIdentEqualTo(BigDecimal value) {
            addCriterion("OB_IDENT =", value, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentNotEqualTo(BigDecimal value) {
            addCriterion("OB_IDENT <>", value, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentGreaterThan(BigDecimal value) {
            addCriterion("OB_IDENT >", value, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OB_IDENT >=", value, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentLessThan(BigDecimal value) {
            addCriterion("OB_IDENT <", value, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OB_IDENT <=", value, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentIn(List<BigDecimal> values) {
            addCriterion("OB_IDENT in", values, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentNotIn(List<BigDecimal> values) {
            addCriterion("OB_IDENT not in", values, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OB_IDENT between", value1, value2, "ident");
            return (Criteria) this;
        }

        public Criteria andIdentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OB_IDENT not between", value1, value2, "ident");
            return (Criteria) this;
        }

        public Criteria andComentarioIsNull() {
            addCriterion("OB_COMENTARIO is null");
            return (Criteria) this;
        }

        public Criteria andComentarioIsNotNull() {
            addCriterion("OB_COMENTARIO is not null");
            return (Criteria) this;
        }

        public Criteria andComentarioEqualTo(String value) {
            addCriterion("OB_COMENTARIO =", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioNotEqualTo(String value) {
            addCriterion("OB_COMENTARIO <>", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioGreaterThan(String value) {
            addCriterion("OB_COMENTARIO >", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioGreaterThanOrEqualTo(String value) {
            addCriterion("OB_COMENTARIO >=", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioLessThan(String value) {
            addCriterion("OB_COMENTARIO <", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioLessThanOrEqualTo(String value) {
            addCriterion("OB_COMENTARIO <=", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioLike(String value) {
            addCriterion("OB_COMENTARIO like", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioNotLike(String value) {
            addCriterion("OB_COMENTARIO not like", value, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioIn(List<String> values) {
            addCriterion("OB_COMENTARIO in", values, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioNotIn(List<String> values) {
            addCriterion("OB_COMENTARIO not in", values, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioBetween(String value1, String value2) {
            addCriterion("OB_COMENTARIO between", value1, value2, "comentario");
            return (Criteria) this;
        }

        public Criteria andComentarioNotBetween(String value1, String value2) {
            addCriterion("OB_COMENTARIO not between", value1, value2, "comentario");
            return (Criteria) this;
        }

        public Criteria andFEnvioIsNull() {
            addCriterion("OB_F_ENVIO is null");
            return (Criteria) this;
        }

        public Criteria andFEnvioIsNotNull() {
            addCriterion("OB_F_ENVIO is not null");
            return (Criteria) this;
        }

        public Criteria andFEnvioEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ENVIO =", value, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioNotEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ENVIO <>", value, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioGreaterThan(Date value) {
            addCriterionForJDBCDate("OB_F_ENVIO >", value, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ENVIO >=", value, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioLessThan(Date value) {
            addCriterionForJDBCDate("OB_F_ENVIO <", value, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ENVIO <=", value, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_ENVIO in", values, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioNotIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_ENVIO not in", values, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_ENVIO between", value1, value2, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andFEnvioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_ENVIO not between", value1, value2, "fEnvio");
            return (Criteria) this;
        }

        public Criteria andURemitenteIsNull() {
            addCriterion("OB_U_REMITENTE is null");
            return (Criteria) this;
        }

        public Criteria andURemitenteIsNotNull() {
            addCriterion("OB_U_REMITENTE is not null");
            return (Criteria) this;
        }

        public Criteria andURemitenteEqualTo(String value) {
            addCriterion("OB_U_REMITENTE =", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteNotEqualTo(String value) {
            addCriterion("OB_U_REMITENTE <>", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteGreaterThan(String value) {
            addCriterion("OB_U_REMITENTE >", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteGreaterThanOrEqualTo(String value) {
            addCriterion("OB_U_REMITENTE >=", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteLessThan(String value) {
            addCriterion("OB_U_REMITENTE <", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteLessThanOrEqualTo(String value) {
            addCriterion("OB_U_REMITENTE <=", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteLike(String value) {
            addCriterion("OB_U_REMITENTE like", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteNotLike(String value) {
            addCriterion("OB_U_REMITENTE not like", value, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteIn(List<String> values) {
            addCriterion("OB_U_REMITENTE in", values, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteNotIn(List<String> values) {
            addCriterion("OB_U_REMITENTE not in", values, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteBetween(String value1, String value2) {
            addCriterion("OB_U_REMITENTE between", value1, value2, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andURemitenteNotBetween(String value1, String value2) {
            addCriterion("OB_U_REMITENTE not between", value1, value2, "uRemitente");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioIsNull() {
            addCriterion("OB_U_DESTINATARIO is null");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioIsNotNull() {
            addCriterion("OB_U_DESTINATARIO is not null");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioEqualTo(String value) {
            addCriterion("OB_U_DESTINATARIO =", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioNotEqualTo(String value) {
            addCriterion("OB_U_DESTINATARIO <>", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioGreaterThan(String value) {
            addCriterion("OB_U_DESTINATARIO >", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioGreaterThanOrEqualTo(String value) {
            addCriterion("OB_U_DESTINATARIO >=", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioLessThan(String value) {
            addCriterion("OB_U_DESTINATARIO <", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioLessThanOrEqualTo(String value) {
            addCriterion("OB_U_DESTINATARIO <=", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioLike(String value) {
            addCriterion("OB_U_DESTINATARIO like", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioNotLike(String value) {
            addCriterion("OB_U_DESTINATARIO not like", value, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioIn(List<String> values) {
            addCriterion("OB_U_DESTINATARIO in", values, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioNotIn(List<String> values) {
            addCriterion("OB_U_DESTINATARIO not in", values, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioBetween(String value1, String value2) {
            addCriterion("OB_U_DESTINATARIO between", value1, value2, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andUDestinatarioNotBetween(String value1, String value2) {
            addCriterion("OB_U_DESTINATARIO not between", value1, value2, "uDestinatario");
            return (Criteria) this;
        }

        public Criteria andFCreacionIsNull() {
            addCriterion("OB_F_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andFCreacionIsNotNull() {
            addCriterion("OB_F_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andFCreacionEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_CREACION =", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionNotEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_CREACION <>", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionGreaterThan(Date value) {
            addCriterionForJDBCDate("OB_F_CREACION >", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_CREACION >=", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionLessThan(Date value) {
            addCriterionForJDBCDate("OB_F_CREACION <", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_CREACION <=", value, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_CREACION in", values, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionNotIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_CREACION not in", values, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_CREACION between", value1, value2, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFCreacionNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_CREACION not between", value1, value2, "fCreacion");
            return (Criteria) this;
        }

        public Criteria andFActuIsNull() {
            addCriterion("OB_F_ACTU is null");
            return (Criteria) this;
        }

        public Criteria andFActuIsNotNull() {
            addCriterion("OB_F_ACTU is not null");
            return (Criteria) this;
        }

        public Criteria andFActuEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ACTU =", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuNotEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ACTU <>", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuGreaterThan(Date value) {
            addCriterionForJDBCDate("OB_F_ACTU >", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ACTU >=", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuLessThan(Date value) {
            addCriterionForJDBCDate("OB_F_ACTU <", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_ACTU <=", value, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_ACTU in", values, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuNotIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_ACTU not in", values, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_ACTU between", value1, value2, "fActu");
            return (Criteria) this;
        }

        public Criteria andFActuNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_ACTU not between", value1, value2, "fActu");
            return (Criteria) this;
        }

        public Criteria andUCreacionIsNull() {
            addCriterion("OB_U_CREACION is null");
            return (Criteria) this;
        }

        public Criteria andUCreacionIsNotNull() {
            addCriterion("OB_U_CREACION is not null");
            return (Criteria) this;
        }

        public Criteria andUCreacionEqualTo(String value) {
            addCriterion("OB_U_CREACION =", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotEqualTo(String value) {
            addCriterion("OB_U_CREACION <>", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionGreaterThan(String value) {
            addCriterion("OB_U_CREACION >", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionGreaterThanOrEqualTo(String value) {
            addCriterion("OB_U_CREACION >=", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionLessThan(String value) {
            addCriterion("OB_U_CREACION <", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionLessThanOrEqualTo(String value) {
            addCriterion("OB_U_CREACION <=", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionLike(String value) {
            addCriterion("OB_U_CREACION like", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotLike(String value) {
            addCriterion("OB_U_CREACION not like", value, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionIn(List<String> values) {
            addCriterion("OB_U_CREACION in", values, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotIn(List<String> values) {
            addCriterion("OB_U_CREACION not in", values, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionBetween(String value1, String value2) {
            addCriterion("OB_U_CREACION between", value1, value2, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUCreacionNotBetween(String value1, String value2) {
            addCriterion("OB_U_CREACION not between", value1, value2, "uCreacion");
            return (Criteria) this;
        }

        public Criteria andUActuIsNull() {
            addCriterion("OB_U_ACTU is null");
            return (Criteria) this;
        }

        public Criteria andUActuIsNotNull() {
            addCriterion("OB_U_ACTU is not null");
            return (Criteria) this;
        }

        public Criteria andUActuEqualTo(String value) {
            addCriterion("OB_U_ACTU =", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotEqualTo(String value) {
            addCriterion("OB_U_ACTU <>", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuGreaterThan(String value) {
            addCriterion("OB_U_ACTU >", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuGreaterThanOrEqualTo(String value) {
            addCriterion("OB_U_ACTU >=", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuLessThan(String value) {
            addCriterion("OB_U_ACTU <", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuLessThanOrEqualTo(String value) {
            addCriterion("OB_U_ACTU <=", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuLike(String value) {
            addCriterion("OB_U_ACTU like", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotLike(String value) {
            addCriterion("OB_U_ACTU not like", value, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuIn(List<String> values) {
            addCriterion("OB_U_ACTU in", values, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotIn(List<String> values) {
            addCriterion("OB_U_ACTU not in", values, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuBetween(String value1, String value2) {
            addCriterion("OB_U_ACTU between", value1, value2, "uActu");
            return (Criteria) this;
        }

        public Criteria andUActuNotBetween(String value1, String value2) {
            addCriterion("OB_U_ACTU not between", value1, value2, "uActu");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioIsNull() {
            addCriterion("OB_MAIL_DESTINATARIO is null");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioIsNotNull() {
            addCriterion("OB_MAIL_DESTINATARIO is not null");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioEqualTo(String value) {
            addCriterion("OB_MAIL_DESTINATARIO =", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioNotEqualTo(String value) {
            addCriterion("OB_MAIL_DESTINATARIO <>", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioGreaterThan(String value) {
            addCriterion("OB_MAIL_DESTINATARIO >", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioGreaterThanOrEqualTo(String value) {
            addCriterion("OB_MAIL_DESTINATARIO >=", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioLessThan(String value) {
            addCriterion("OB_MAIL_DESTINATARIO <", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioLessThanOrEqualTo(String value) {
            addCriterion("OB_MAIL_DESTINATARIO <=", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioLike(String value) {
            addCriterion("OB_MAIL_DESTINATARIO like", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioNotLike(String value) {
            addCriterion("OB_MAIL_DESTINATARIO not like", value, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioIn(List<String> values) {
            addCriterion("OB_MAIL_DESTINATARIO in", values, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioNotIn(List<String> values) {
            addCriterion("OB_MAIL_DESTINATARIO not in", values, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioBetween(String value1, String value2) {
            addCriterion("OB_MAIL_DESTINATARIO between", value1, value2, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andMailDestinatarioNotBetween(String value1, String value2) {
            addCriterion("OB_MAIL_DESTINATARIO not between", value1, value2, "mailDestinatario");
            return (Criteria) this;
        }

        public Criteria andRespuestaIsNull() {
            addCriterion("OB_RESPUESTA is null");
            return (Criteria) this;
        }

        public Criteria andRespuestaIsNotNull() {
            addCriterion("OB_RESPUESTA is not null");
            return (Criteria) this;
        }

        public Criteria andRespuestaEqualTo(String value) {
            addCriterion("OB_RESPUESTA =", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaNotEqualTo(String value) {
            addCriterion("OB_RESPUESTA <>", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaGreaterThan(String value) {
            addCriterion("OB_RESPUESTA >", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaGreaterThanOrEqualTo(String value) {
            addCriterion("OB_RESPUESTA >=", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaLessThan(String value) {
            addCriterion("OB_RESPUESTA <", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaLessThanOrEqualTo(String value) {
            addCriterion("OB_RESPUESTA <=", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaLike(String value) {
            addCriterion("OB_RESPUESTA like", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaNotLike(String value) {
            addCriterion("OB_RESPUESTA not like", value, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaIn(List<String> values) {
            addCriterion("OB_RESPUESTA in", values, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaNotIn(List<String> values) {
            addCriterion("OB_RESPUESTA not in", values, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaBetween(String value1, String value2) {
            addCriterion("OB_RESPUESTA between", value1, value2, "respuesta");
            return (Criteria) this;
        }

        public Criteria andRespuestaNotBetween(String value1, String value2) {
            addCriterion("OB_RESPUESTA not between", value1, value2, "respuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaIsNull() {
            addCriterion("OB_F_RESPUESTA is null");
            return (Criteria) this;
        }

        public Criteria andFRespuestaIsNotNull() {
            addCriterion("OB_F_RESPUESTA is not null");
            return (Criteria) this;
        }

        public Criteria andFRespuestaEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_RESPUESTA =", value, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaNotEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_RESPUESTA <>", value, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaGreaterThan(Date value) {
            addCriterionForJDBCDate("OB_F_RESPUESTA >", value, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_RESPUESTA >=", value, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaLessThan(Date value) {
            addCriterionForJDBCDate("OB_F_RESPUESTA <", value, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("OB_F_RESPUESTA <=", value, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_RESPUESTA in", values, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaNotIn(List<Date> values) {
            addCriterionForJDBCDate("OB_F_RESPUESTA not in", values, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_RESPUESTA between", value1, value2, "fRespuesta");
            return (Criteria) this;
        }

        public Criteria andFRespuestaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("OB_F_RESPUESTA not between", value1, value2, "fRespuesta");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated do_not_delete_during_merge Fri Aug 26 10:50:15 CEST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AJ_OBSERVACIONES
     *
     * @mbggenerated Fri Aug 26 10:50:15 CEST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}