package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Descripciones;
import es.ise.ciceron.model.DescripcionesExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface DescripcionesMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int countByExample(DescripcionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int deleteByExample(DescripcionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal idDescripcion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int insert(Descripciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int insertSelective(Descripciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    List<Descripciones> selectByExample(DescripcionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    Descripciones selectByPrimaryKey(BigDecimal idDescripcion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int updateByExampleSelective(@Param("record") Descripciones record, @Param("example") DescripcionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int updateByExample(@Param("record") Descripciones record, @Param("example") DescripcionesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int updateByPrimaryKeySelective(Descripciones record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DESCRIPCIONES
     *
     * @mbggenerated Wed Aug 24 13:51:43 CEST 2011
     */
    int updateByPrimaryKey(Descripciones record);
}