package es.ise.ciceron.mapper;

import es.ise.ciceron.model.ListaDePliegos;
import es.ise.ciceron.model.ListaDePliegosExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ListaDePliegosMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int countByExample(ListaDePliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<ListaDePliegos> selectByExampleWithBLOBs(ListaDePliegosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VERSIONES_PLIEGOS_V
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<ListaDePliegos> selectByExample(ListaDePliegosExample example);
}