package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Normativa;
import es.ise.ciceron.model.NormativaExample;
import java.math.BigDecimal;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface NormativaMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NORMATIVA
     *
     * @mbggenerated Fri Jul 01 12:35:22 CEST 2011
     */
    int countByExample(NormativaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NORMATIVA
     *
     * @mbggenerated Fri Jul 01 12:35:22 CEST 2011
     */
    List<Normativa> selectByExample(NormativaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NORMATIVA
     *
     * @mbggenerated Fri Jul 01 12:35:22 CEST 2011
     */
    Normativa selectByPrimaryKey(BigDecimal id);
}