package es.ise.ciceron.mapper;

import es.ise.ciceron.model.OpcionMenu;
import es.ise.ciceron.model.OpcionMenuExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface OpcionMenuMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int countByExample(OpcionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int deleteByExample(OpcionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int insert(OpcionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int insertSelective(OpcionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    List<OpcionMenu> selectByExample(OpcionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    OpcionMenu selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByExampleSelective(@Param("record") OpcionMenu record, @Param("example") OpcionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByExample(@Param("record") OpcionMenu record, @Param("example") OpcionMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByPrimaryKeySelective(OpcionMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OPCIONES_MENUS
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByPrimaryKey(OpcionMenu record);
}