package es.ise.ciceron.mapper;

import es.ise.ciceron.model.OtrasUnidades;
import es.ise.ciceron.model.OtrasUnidadesExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface OtrasUnidadesMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int countByExample(OtrasUnidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int deleteByExample(OtrasUnidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int insert(OtrasUnidades record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int insertSelective(OtrasUnidades record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    List<OtrasUnidades> selectByExample(OtrasUnidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    OtrasUnidades selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int updateByExampleSelective(@Param("record") OtrasUnidades record, @Param("example") OtrasUnidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int updateByExample(@Param("record") OtrasUnidades record, @Param("example") OtrasUnidadesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int updateByPrimaryKeySelective(OtrasUnidades record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_OTRAS_UNIDADES
     *
     * @mbggenerated Thu Jul 07 13:39:24 CEST 2011
     */
    int updateByPrimaryKey(OtrasUnidades record);
}