package es.ise.ciceron.mapper;

import es.ise.ciceron.model.ParametrosSolicitudes;
import es.ise.ciceron.model.ParametrosSolicitudesExample;
import java.math.BigDecimal;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ParametrosSolicitudesMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTA.PARAMETROS_SOLICITUDES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(ParametrosSolicitudesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTA.PARAMETROS_SOLICITUDES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<ParametrosSolicitudes> selectByExample(ParametrosSolicitudesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONTA.PARAMETROS_SOLICITUDES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    ParametrosSolicitudes selectByPrimaryKey(BigDecimal id);
}