package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Procedimiento;
import es.ise.ciceron.model.ProcedimientoExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface ProcedimientoMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROCEDIMIENTOS_V
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(ProcedimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROCEDIMIENTOS_V
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<Procedimiento> selectByExample(ProcedimientoExample example);
}