package es.ise.ciceron.mapper;

import es.ise.ciceron.model.PuntosEditados;
import es.ise.ciceron.model.PuntosEditadosExample;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface PuntosEditadosMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOSEDITADOS_V
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(PuntosEditadosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_PUNTOSEDITADOS_V
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<PuntosEditados> selectByExample(PuntosEditadosExample example);
}