package es.ise.ciceron.mapper;

import es.ise.ciceron.model.TipoServicio;
import es.ise.ciceron.model.TipoServicioExample;
import java.math.BigDecimal;
import java.util.List;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface TipoServicioMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPOS_SERVICIOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    int countByExample(TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPOS_SERVICIOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    List<TipoServicio> selectByExample(TipoServicioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIPOS_SERVICIOS
     *
     * @mbggenerated Wed Aug 24 09:41:32 CEST 2011
     */
    TipoServicio selectByPrimaryKey(BigDecimal id);
}