package es.ise.ciceron.mapper;

import es.ise.ciceron.model.Tipologia;
import es.ise.ciceron.model.TipologiaExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface TipologiaMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int countByExample(TipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int deleteByExample(TipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int insert(Tipologia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int insertSelective(Tipologia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    List<Tipologia> selectByExample(TipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    Tipologia selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByExampleSelective(@Param("record") Tipologia record, @Param("example") TipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByExample(@Param("record") Tipologia record, @Param("example") TipologiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByPrimaryKeySelective(Tipologia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AJ_TIPOLOGIA_INFORMES
     *
     * @mbggenerated Mon Aug 08 10:45:32 CEST 2011
     */
    int updateByPrimaryKey(Tipologia record);
}