package es.ise.ciceron.mapper;

import es.ise.ciceron.model.UnidadesContratacion;
import es.ise.ciceron.model.UnidadesContratacionExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.Mapper;

@Mapper
public interface UnidadesContratacionMapper extends CiceronMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int countByExample(UnidadesContratacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int deleteByExample(UnidadesContratacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int insert(UnidadesContratacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int insertSelective(UnidadesContratacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    List<UnidadesContratacion> selectByExample(UnidadesContratacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    UnidadesContratacion selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByExampleSelective(@Param("record") UnidadesContratacion record, @Param("example") UnidadesContratacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByExample(@Param("record") UnidadesContratacion record, @Param("example") UnidadesContratacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByPrimaryKeySelective(UnidadesContratacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UNIDADES_CONTRATACION
     *
     * @mbggenerated Thu Jun 09 13:50:46 CEST 2011
     */
    int updateByPrimaryKey(UnidadesContratacion record);
}